/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shinseungchan_ssd_views_CameraActivity */

#ifndef _Included_com_example_shinseungchan_ssd_views_CameraActivity
#define _Included_com_example_shinseungchan_ssd_views_CameraActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_shinseungchan_ssd_views_CameraActivity_PERMISSIONS_REQUEST_CODE
#define com_example_shinseungchan_ssd_views_CameraActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_shinseungchan_ssd_views_CameraActivity
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_shinseungchan_ssd_views_CameraActivity_loadCascade
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_shinseungchan_ssd_views_CameraActivity
 * Method:    detect
 * Signature: (JJJJ)V
 */
JNIEXPORT jint JNICALL Java_com_example_shinseungchan_ssd_views_CameraActivity_detect
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
